name: Deploy CartService to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'CartService/**'
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: 'dev'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Build and Push Docker image
      uses: azure/docker-login@v1
      with:
            login-server: ${{ secrets.ACR_NAME }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/cart-service:${{ github.sha }}  -f ./CartService/CartService.Api/Dockerfile  ./CartService
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/cart-service:${{ github.sha }}


    - name: Set AKS context
      run: |
        az aks get-credentials \
          --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
          --name ${{ secrets.AKS_CLUSTER_NAME }} \
          --overwrite-existing


    - name: Deploy to AKS
      run: |
        kubectl set image deployment/cart-service cart-service=${{ secrets.ACR_NAME }}.azurecr.io/cart-service:${{ github.sha }}
        kubectl apply -f CartService/k8s/